
torchrun --nnodes=1 --nproc_per_node 2  --master_port 29503 \
    -m opensora.sample.sample_t2v_sp \
    --model_path models/93x720p \
    --num_frames 93 \
    --height 480 \
    --width 640 \
    --cache_dir "../cache_dir" \
    --text_encoder_name google/mt5-xxl \
    --text_prompt examples/prompt_list_0.txt \
    --ae CausalVAEModel_D4_4x8x8 \
    --ae_path models/vae \
    --save_img_path "./sample/sample_video_test_93x720p_480p" \
    --fps 24 \
    --guidance_scale 7.5 \
    --num_sampling_steps 20 \
    --enable_tiling \
    --tile_overlap_factor 0.125 \
    --max_sequence_length 512 \
    --sample_method EulerAncestralDiscrete \
    --model_type "dit" 